openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Asset
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/assets:
    get:
      tags:
        - Device Management - Asset
      summary: Get the Assets Definitions of a single Device
      operationId: deviceAssetList
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      responses:
        200:
          description: The list of Assets definition of a single Device
          content:
            application/json:
              schema:
                $ref: './deviceAsset.yaml#/components/schemas/deviceAssetDefinitions'
        400:
          $ref: '../openapi.yaml#/components/responses/illegalArgument'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        409:
          $ref: '../openapi.yaml#/components/responses/conflictDeviceNotConnected'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    post:
      tags:
        - Device Management - Asset
      summary: Get the Assets Definitions of a single Device filtered
      operationId: deviceAssetListFiltered
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
        - $ref: '../device/device.yaml#/components/parameters/timeout'
      requestBody:
        description: An object containing the list of Assets to use as a filter. If no DeviceAsset is specified, all DeviceAsset will be read.
        content:
          application/json:
            schema:
              $ref: './deviceAsset.yaml#/components/schemas/deviceAssetDefinitionsFilter'
            examples:
              Select all:
                value:
                  deviceAsset:
                    -
              Filtered:
                value:
                  deviceAsset:
                    - name: Asset-1
      responses:
        200:
          description: The list of Assets definition of a single Device according to the filter
          content:
            application/json:
              schema:
                $ref: './deviceAsset.yaml#/components/schemas/deviceAssetDefinitions'
        400:
          $ref: '../openapi.yaml#/components/responses/illegalArgument'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
