openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Current Account
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

components:
  schemas:
    currentAccountUpdateRequest:
      type: object
      description: An object with all the information needed to create a new Account
      properties:
        description:
          type: string
        optlock:
          $ref: '../openapi.yaml#/components/schemas/optlock'
        organization:
          type: object
          $ref: '../accounts/accounts.yaml#/components/schemas/organization'
      required:
        - optlock
        - organization
      example:
        description: Acme Inc.'s Account
        optlock: 2
        organization:
          name: ACME Inc.
          personName: Wile Ethelbert Coyote
          email: wile.coyote@acme.inc
          phoneNumber: +1 (555) 123 4567
          addressLine1: 123 Looney Tunes Drive
          addressLine2: Block 1
          addressLine3: Apartment 25
          zipPostCode: '00100'
          city: Somewhere City
          stateProvinceCounty: Green County, GC
          country: United States

paths:
  /account:
    get:
      tags:
        - Current Account
      summary: Fetch current account
      description: Get the details of a current Account.
      operationId: getCurrentAccount
      responses:
        200:
          description: The details of the current Account
          content:
            application/json:
              schema:
                $ref: '../accounts/accounts.yaml#/components/schemas/account'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    put:
      tags:
        - Current Account
      summary: Update the details for the current Account
      operationId: putCurrentAccount
      requestBody:
        description: An object containing the new properties for the current Account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/currentAccountUpdateRequest'
        required: true
      responses:
        200:
          description: The details of the updated Account
          content:
            application/json:
              schema:
                $ref: '../accounts/accounts.yaml#/components/schemas/account'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
      description: Update the details of a given Account, according to the `accountId` path parameter. Please note that some fields may be readonly for integrity purposes.