language: java
jdk:
  - oraclejdk8
script: ./travis.sh

# The following upgrades Java during the build in
# order to work around an older Java 8 compiler issue
# which has problems infering types. Travis ships a
# rather old Java 8 version in its images.

addons:
  apt:
    packages:
      - oracle-java8-installer 