language: java

jdk:
  - oraclejdk8

sudo: false

install:
  - echo ==== Setting up toolchain.xml ====
  - ls /usr/lib/jvm
  - ls
  - cp build-tools/src/main/toolchains/travis-ci.xml ~/.m2/toolchains.xml
  - echo ==== Setting up Maven 3.3 for Travis ====
  - wget -O maven.tar.gz http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - mkdir maven
  - cd maven ; tar --strip-components 1 -xzf ../maven.tar.gz ; cd ..
  - chmod a+x maven/bin/mvn

before_script:
  - export M2_HOME=$PWD/maven
  - export PATH=$PWD/maven/bin:${PATH}
  - hash -r

script: ./travis.sh

after_script:
  - bash <(curl -s https://codecov.io/bash)

# The following upgrades Java during the build in
# order to work around an older Java 8 compiler issue
# which has problems infering types. Travis ships a
# rather old Java 8 version in its images.

addons:
  apt:
    packages:
      - oracle-java8-installer 