services:
  message-broker:
    ports:
      - ${KAPUA_BROKER_DEBUG_PORT:-5005}:5005
    environment:
      - DEBUG_ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=${KAPUA_BROKER_DEBUG_SUSPEND:-n},address=*:5005