openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Users Credentials
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/users/{userId}/credentials/password/_reset:
    post:
      description: Reset the password credential for the specified user, or creates one if there is none
      tags:
        - Users Credentials
      summary: Reset the password of a user
      operationId: usersCredentialsPasswordReset
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../user/user.yaml#/components/parameters/userId'
      requestBody:
        description: The new password
        content:
          application/json:
            schema:
              $ref: '../userCredentials/user-credentials.yaml#/components/schemas/passwordResetRequest'
        required: true
      responses:
        204:
          description: The updated or created Credential
          content:
            application/json:
              schema:
                $ref: '../credential/credential.yaml#/components/schemas/credential'
        400:
          $ref: '../openapi.yaml#/components/responses/illegalArgument'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'