openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Users Credentials
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/users/{userId}/credentials/_count:
    post:
      tags:
        - Users Credentials
      summary: Count the Credentials for the User
      operationId: usersCredentialsCount
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../user/user.yaml#/components/parameters/userId'
      requestBody:
        $ref: '../openapi.yaml#/components/requestBodies/kapuaQuery'
      responses:
        200:
          $ref: '../openapi.yaml#/components/responses/countResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
  /{scopeId}/user/{userId}/credentials/_count:
    post:
      deprecated: true
      description:
        This resource is deprecated and will be removed in future releases. Please make use of /{scopeId}/users/{userId}/credentials/_count (plural userS)
      tags:
        - Users Credentials
      summary: Count the Credentials for the User
      operationId: user_s_CredentialsCount
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../user/user.yaml#/components/parameters/userId'
      requestBody:
        $ref: '../openapi.yaml#/components/requestBodies/kapuaQuery'
      responses:
        200:
          $ref: '../openapi.yaml#/components/responses/countResult'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'