openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Credential
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0
paths:
  /user/credentials/{credentialId}/_reset:
    post:
      deprecated: true
      description: >
        This resource is deprecated and will be removed in future releases. Please make use of:
        POST /{scopeId}/users/{userId}/credentials/password/_reset (for admins resetting a user's password)
        or
        POST /user/credentials/password (for the user changing its own password) instead
      tags:
        - User Credentials
      summary: Reset the password of a Credential
      operationId: credentialPasswordReset
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../credential/credential.yaml#/components/parameters/credentialId'
      requestBody:
        description: The new password
        content:
          application/json:
            schema:
              $ref: './user-credentials.yaml#/components/schemas/passwordResetRequest'
        required: true
      responses:
        204:
          description: The updated Credential
          content:
            application/json:
              schema:
                $ref: '../credential/credential.yaml#/components/schemas/credential'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
  /{scopeId}/user/credentials/{credentialId}/_reset:
    post:
      deprecated: true
      description: >
        This resource is deprecated and will be removed in future releases. Please make use of:
        POST /{scopeId}/users/{userId}/credentials/password/_reset (for admins resetting a user's password)
        or
        POST /user/credentials/password (for the user changing its own password) instead
      tags:
        - User Credentials
      summary: Reset the password of a Credential
      operationId: scopeIdCredentialPasswordReset
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../credential/credential.yaml#/components/parameters/credentialId'
      requestBody:
        description: The new password
        content:
          application/json:
            schema:
              $ref: './user-credentials.yaml#/components/schemas/passwordResetRequest'
        required: true
      responses:
        204:
          description: The updated Credential
          content:
            application/json:
              schema:
                $ref: '../credential/credential.yaml#/components/schemas/credential'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
