version: '3.1'

services:
  db:
    container_name: db
    image: kapua/kapua-sql:${IMAGE_VERSION}
    ports:
      - "3306:3306"
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=kapua-datastore
      - discovery.type=single-node
      - transport.host=_site_
      - transport.ping_schedule=-1
      - transport.tcp.connect_timeout=30s
  events-broker:
    container_name: events-broker
    image: kapua/kapua-events-broker:${IMAGE_VERSION}
    ports:
      - "5672:5672"
  message-broker:
    image: kapua/kapua-broker-artemis:${IMAGE_VERSION}
    container_name: message-broker
    expose:
      - 1893
    ports:
      - "1883:1883"
      - "1893:1893"
      - "5682:5672"
      - "61616:61616"
    depends_on:
      - db
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_DATASTORE
      - LOGBACK_LOG_LEVEL
  service-authentication:
    image: kapua/kapua-service-authentication:${IMAGE_VERSION}
    container_name: service-auth
    ports:
      - 8100:8080
    depends_on:
      - db
      - events-broker
    environment:
      - LOGBACK_LOG_LEVEL
  consumer-telemetry:
    container_name: consumer-telemetry
    image: kapua/kapua-consumer-telemetry:${IMAGE_VERSION}
    ports:
      - "8090:8080"
    depends_on:
      - db
      - es
      - events-broker
      - message-broker
    environment:
      - BROKER_URL
      - CRYPTO_SECRET_KEY
      - LOGBACK_LOG_LEVEL
  consumer-lifecycle:
    container_name: consumer-lifecycle
    image: kapua/kapua-consumer-lifecycle:${IMAGE_VERSION}
    ports:
      - "8091:8080"
    depends_on:
      - db
      - events-broker
      - message-broker
    environment:
      - BROKER_URL
      - CRYPTO_SECRET_KEY
      - LOGBACK_LOG_LEVEL
  kapua-console:
    container_name: kapua-console
    image: kapua/kapua-console:${IMAGE_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - es
      - events-broker
      - message-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_DATASTORE
      - LOGBACK_LOG_LEVEL
  kapua-api:
    container_name: kapua-api
    image: kapua/kapua-api:${IMAGE_VERSION}
    ports:
      - "8081:8080"
      - "8444:8443"
    depends_on:
      - db
      - es
      - events-broker
      - message-broker
    environment:
      - API_CORS_ORIGINS_ALLOWED
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_DATASTORE
      - LOGBACK_LOG_LEVEL
      - SWAGGER=${KAPUA_SWAGGER_ENABLE:-true}
      - AUTH_TOKEN_TTL=${AUTH_TOKEN_TTL:-1800000}
      - REFRESH_AUTH_TOKEN_TTL=${REFRESH_AUTH_TOKEN_TTL:-18000000}
      - CORS_ENDPOINTS_REFRESH_INTERVAL=${CORS_ENDPOINTS_REFRESH_INTERVAL:-60}
  job-engine:
    container_name: job-engine
    image: kapua/kapua-job-engine:${IMAGE_VERSION}
    expose:
      - 8080
    depends_on:
      - db
      - events-broker
      - message-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_DATASTORE
      - LOGBACK_LOG_LEVEL
