openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Configurations
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths:
  /{scopeId}/devices/{deviceId}/configurations/_settings:
    get:
      tags:
        - Device Management - Configuration
      summary: Gets the settings of the Device Configurations Store settings of this Device
      operationId: getDeviceConfigurationsStoreSettings
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
      responses:
        200:
          description: The Device Management Settings retrieved
          content:
            application/json:
              schema:
                $ref: './deviceConfiguration.yaml#/components/schemas/deviceConfigurationStoreSettings'
        400:
          $ref: '../openapi.yaml#/components/responses/illegalArgument'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
    put:
      tags:
        - Device Management - Configuration
      summary: Applies the given settings to the Device Configurations Store settings of this Device
      operationId: putDeviceConfigurationsStoreSettings
      parameters:
        - $ref: '../openapi.yaml#/components/parameters/scopeId'
        - $ref: '../device/device.yaml#/components/parameters/deviceId'
      requestBody:
        description: The Device Configurations Store Settings for this Device
        content:
          application/json:
            schema:
              $ref: './deviceConfiguration.yaml#/components/schemas/deviceConfigurationStoreSettings'
        required: true
      responses:
        204:
          description: The Device Management Settings have been applied
        400:
          $ref: '../openapi.yaml#/components/responses/illegalArgument'
        401:
          $ref: '../openapi.yaml#/components/responses/unauthenticated'
        403:
          $ref: '../openapi.yaml#/components/responses/subjectUnauthorized'
        404:
          $ref: '../openapi.yaml#/components/responses/entityNotFound'
        409:
          $ref: '../openapi.yaml#/components/responses/conflictDeviceNotConnected'
        500:
          $ref: '../openapi.yaml#/components/responses/kapuaError'
