services:
  keycloak:
    container_name: kapua-keycloak
    image: kapua/kapua-keycloak:${IMAGE_VERSION}
    ports:
      - "${KEYCLOAK_PORT_HTTP}:9090"
      - "${KEYCLOAK_PORT_HTTPS}:8443"
    volumes:
      - "../target/compose/sso/certs:/etc/x509/https"
    environment:
      - KAPUA_CONSOLE_URL
      - KEYCLOAK_ADMIN_USER
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_HOST_NAME
      - KEYCLOAK_PORT_HTTP
      - KEYCLOAK_PORT_HTTPS
      - SSO_CERT_FILE
      - SSO_KEY_FILE
      - KEYCLOAK_SSL_ENABLE

