name: Security Scan
on:
  push:
    branches:
      - 'develop'
      - 'release-**'

env:
  BUILD_OPTS: ""
  MAVEN_OPTS: "-Xmx4096m"

jobs:
  # Documentation: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html
  owasp-dependency-check:
    name: Owasp Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checks out a copy of the repository on the ubuntu-latest machine
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'maven'
      - uses: actions/cache@v3 # Cache local Maven repository to reuse dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B ${BUILD_OPTS} -DskipTests -Psecurity-scan verify